### ISSUE TITLE
make date structs comparabler

### ISSUE THREAD

**Issue by jnordwick** [cassioneri/eaf#2]
why don't you use uint32 or similar inthe struct and lay it out in little endian order (day, month, year) (eg, uint16, uint16, uint32 or uint8, uint8, uint16) then you can do a simple less/greater than to compare the dates?

**Comment by cassioneri** [comment]
Thanks for your question/suggestion.

IIUIC, you're thinking about some bit-twiddling similar to [1] or, perhaps, using the spaceship operator as in [2].

Indeed, such things are possible. However the point of this project is not to be a full-fledged implementation of a date class. This is just the supplementary material for the published paper and we hope it allows other researchers to reproduce our results (correctness and benchmarks). For this purpose, we keep it minimal and "as simple as possible" (in our own interpretation of the term.)

Notice, for instance, that [1] and [2] require C++20 and to make it more accessible, we preferred making it compilable against previous standards (`CMakeLists.txt` sets it to C++14). It's true that [1] could be adapted to older standards (e.g., using `std::memcpy`) but, as you correctly pointed out, this only works on little-endian systems. Again, we wish to make it available for more people and platforms.

Best wishes,
Cassio.

[1] https://godbolt.org/z/1dqfes6Mq
[2] https://godbolt.org/z/as7e381Wx

**Comment by jnordwick** [comment]
You get the idea. I'm about to start a write of new floating point printing code and a new tsc/cal/date lib in zig. (gotta log fast). i'll clear the pre results with you. Absolutely great talk too, loved it.

**Comment by cassioneri** [comment]
@jnordwick Thanks for your kind words. I'm glad you liked the talk. 

Since you are interested in implementing our algorithms in zig, you might also be interested in this discussion: https://github.com/ziglang/zig/issues/8396

**Comment by jnordwick** [comment]
Thank you! I did your algo last night but want to generalize it to different types (eg, there can be some data dependencies bc of how the registers work with using bytes inside a struct but you want to keep it all in a 64 or 32 bit unsigned so need to do things like  apply a bias to the year like a  floating point exponent to keep them trivially comparable), but good to know others are working on it. I tend to go for absolute lowest latency so mine would probably be less general than theirs -- theirs being more appropriate for a standard library. I'll try to contact them though, thanks again.
