### ISSUE TITLE
Why use `uint32_t` for `date_t`'s `month` and `day`?

### ISSUE THREAD

**Issue by clickingbuttons** [cassioneri/eaf#4]
Thanks for providing this helpful supplemental material!

I understand the decision doesn't really matter because it's not the subject of the paper or benchmark. However, I'm curious the rationale since only Julian and Gregorian calendars are implemented.

For these calendars the month can fit in an `uint8_t` [1-13] and the day in an `uint8_t` [1-31]. Was there a reason for selecting a larger type?

**Comment by cassioneri** [comment]
Sorry for the late reply (I've been busy preparing the presentation of my next algorithm in the forthcoming C++Now 2024  conference -- watch this space).

A couple of considerations follow.

Firstly, as you said, the code here especially `date_t`  is not meant to be a full fledged date class. It's only a reference implementation from which library writers can get inspiration for their own.

You're completely right on suggesting that month and day should be stored as `uint8_t` especially, like in some of C++ standard library implementations, if `std::year` is stored as `int16_t`. By using  `uint8_t` for month and day, their `std::chrono::year_month_day` class doesn't  waste any bit (not even padding bits) and is very cache-friendly.

Finally, at least on x64 architectures, instructions on 32 bits data seem a bit faster than on 8 and 16 bits data. Hence, it's better to keep the arithmetic operations as much as possible on `uint32_t` and only at the very late stage convert it to `uint8_t` for storage in memory. This conversion is probably "free" but, just in case, I didn't want to add them to the measurements and thus, I kept month and day as `uint32_t`. I confess that I might be hand waving here but, IIRC, I did look into this point when writing this implementation.

**Comment by clickingbuttons** [comment]
Thanks for your reply, that makes a lot of sense. In today's world I suspect a `u8`'s memory benefits will far outweigh `u32`'s compute benefits. 

Edit: I found the teaser https://schedule.cppnow.org/session/a-new-dragon-in-the-den-fast-conversion-from-floating-point-numbers/

I hope you can beat Ryu!
